# For original graph

Default:
  model_type: stegcn
  init_graph: original
  subset_of_weights: all
  hessian_structure: diag
  ste_thresh: 0.5
  n_hypersteps: 10
  n_data_rand_splits: 10
  n_epochs_burnin: 50
  marglik_frequency: 10
  weight_decay: 5.0e-5
  n_repeats: 1
  dropout_p: 0.5
  optimizer: adam
  early_stop: False
  grad_norm: True
  gpu_num: 1


Cora:
  dataset: cora
  hidden_channels: 64
  n_epochs: 200
  n_epochs_burnin: 50
  n_hyper_stop: 150
  marglik_frequency: 20
  lr: 0.001
  lr_adj: 0.8
  momentum_adj: 0.9
  res: False
  norm: none
  symmetric: True
  train_masked_update: False
  weight_decay_adj: 5.0e-4
  
Citeseer:
  dataset: citeseer
  hidden_channels: 64
  n_epochs: 100
  n_epochs_burnin: 50
  n_hyper_stop: 100
  marglik_frequency: 10
  lr: 0.001
  lr_adj: 1.5
  momentum_adj: 0.9
  res: False
  norm: none
  symmetric: True
  train_masked_update: False
  weight_decay_adj: 5.0e-4

Cornell:
  dataset: cornell
  hidden_channels: 64
  n_epochs: 400 # 1000
  n_epochs_burnin: 10
  n_hyper_stop: 350 # 900
  marglik_frequency: 20
  lr: 0.03
  lr_adj: 10
  momentum_adj: 0.9
  res: True
  norm: layer
  symmetric: True
  train_masked_update: False
  weight_decay_adj: 5.0e-4
  weight_decay: 5.0e-4
  early_stop: False

Texas:
  dataset: texas
  hidden_channels: 128
  n_epochs: 400
  n_epochs_burnin: 10
  n_hyper_stop: 350
  marglik_frequency: 20
  lr: 0.03
  lr_adj: 10
  momentum_adj: 0.9
  res: True
  norm: layer
  symmetric: True
  train_masked_update: False
  weight_decay_adj: 5.0e-4
  weight_decay: 5.0e-4
  early_stop: False

Wisconsin:
  dataset: wisconsin
  hidden_channels: 128
  n_epochs: 400
  n_epochs_burnin: 10
  n_hyper_stop: 400
  marglik_frequency: 20
  lr: 0.02
  lr_adj: 10
  momentum_adj: 0.9
  res: True
  norm: layer
  symmetric: True
  train_masked_update: False
  weight_decay_adj: 5.0e-4
  weight_decay: 5.0e-4
  early_stop: False

Banana:
  dataset: banana
  num_layers: 1
  hidden_channels: 64
  n_epochs: 200
  n_epochs_burnin: 50
  n_hyper_stop: 150
  marglik_frequency: 20
  lr: 0.01
  lr_adj: 2
  momentum_adj: 0.9
  res: False
  norm: none
  symmetric: True
  train_masked_update: False
  weight_decay_adj: 5.0e-4
  weight_decay: 5.0e-4
  early_stop: False
  n_data_rand_splits: 1
  n_repeats: 1

Circle:
  num_layers: 2
  dataset: circle
  hidden_channels: 32
  n_data_rand_splits: 1
  n_repeats: 1
  n_epochs: 200
  lr: 0.001
  n_epochs_burnin: 10
  n_hyper_stop: 150
  marglik_frequency: 10
  momentum_adj: 0.9
  lr_adj: 5
  res: False
  norm: layer
  symmetric: True
  train_masked_update: False
  weight_decay_adj: 2.0e-3
  weight_decay: 5.0e-5
  early_stop: False
